services:
  - type: web
    name: study-space-secured
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python "views updated/main.py"
    autoDeploy: true
